spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mall.mysql:3306/mall-sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qweQWE915519qwe
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      serverAddr: 127.0.0.1:8848
      config:
        namespace: f8a8de77-bba8-41ba-ac33-cd980e721880
        group: coupon
  config:
    import:
      - nacos:${spring.application.name}.properties?refresh=true
  application:
    name: mall-coupon

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  global-config:
    db-config:
      id-type: auto
server:
  port: 3001

coupon:
  user:
    name: zhangsan
    age: 18
